### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by despoinamusica39** [whoiskekeanyway/itunes-app#1]
hello there...happy new year!could you please complete the project for itunes?for download it from your github?I have no idea from programming!!!I will preciate it so much!!!

**Comment by despoinamusica39** [comment]
answer me please!!!

**Comment by whoiskekeanyway** [comment]
I do not understand you. What do you need ?

**Comment by despoinamusica39** [comment]
look..good morning and nice to meet you!I am Despoina from Greece!lmy friend I like spanish music so much..but I am new on developing!!! but I have no idea how programming to project for use it..could you make it ready and download it from your github?I will preciate it so muchhhhhhhhhhhhh!!!

**Comment by despoinamusica39** [comment]
Install dependencies for server
npm install

# Install dependencies for client
npm run client-install

# Run the client & server with concurrently
npm run dev

# Run the Express server only
npm run server

# Run the React client only
npm run client

# Server runs on http://localhost:5000 and client on http://localhost:3000

**Comment by whoiskekeanyway** [comment]
Just install the dependencies

**Comment by despoinamusica39** [comment]
but how?could you help me pleaseeeeeeeeeeee?????????
